-- Sathyagrahi Academy source-locked NEET Sep-Dec 2026 master study calendar.
-- Sources: approved Biology, Chemistry and Physics Master Plan PDFs.

create table if not exists public.academy_study_plan_chapters (
  id bigint generated by default as identity primary key,
  subject text not null check (subject in ('Biology','Chemistry','Physics')),
  plan_group text not null,
  unit_no integer not null,
  chapter_no integer not null,
  chapter text not null,
  study_start date not null,
  study_end date not null,
  r1_date date not null,
  r2_date date not null,
  r3_date date not null,
  r4_date date not null,
  planned_minutes integer not null default 240 check (planned_minutes > 0),
  source_year integer not null default 2026,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (subject, chapter_no),
  check (study_end >= study_start)
);

alter table public.academy_study_plan_chapters enable row level security;
revoke all on table public.academy_study_plan_chapters from anon, authenticated;
grant select on table public.academy_study_plan_chapters to authenticated;
grant select, insert, update, delete on table public.academy_study_plan_chapters to service_role;

drop policy if exists academy_study_plan_authenticated_read on public.academy_study_plan_chapters;
create policy academy_study_plan_authenticated_read on public.academy_study_plan_chapters for select to authenticated using (true);

insert into public.academy_study_plan_chapters
(subject,plan_group,unit_no,chapter_no,chapter,study_start,study_end,r1_date,r2_date,r3_date,r4_date,planned_minutes)
values
('Biology','Diversity in Living World',1,1,'The Living World','2026-09-07','2026-09-07','2026-09-08','2026-09-14','2026-09-28','2026-10-22',240),
('Biology','Diversity in Living World',1,2,'Biological Classification','2026-09-08','2026-09-09','2026-09-10','2026-09-16','2026-09-30','2026-10-24',240),
('Biology','Diversity in Living World',1,3,'Plant Kingdom','2026-09-10','2026-09-12','2026-09-13','2026-09-19','2026-10-03','2026-10-27',240),
('Biology','Diversity in Living World',1,4,'Animal Kingdom','2026-09-13','2026-09-16','2026-09-17','2026-09-23','2026-10-07','2026-10-31',240),
('Biology','Structural Organisation in Animals and Plants',2,5,'Morphology of Flowering Plants','2026-09-18','2026-09-20','2026-09-21','2026-09-27','2026-10-11','2026-11-04',240),
('Biology','Structural Organisation in Animals and Plants',2,6,'Anatomy of Flowering Plants','2026-09-21','2026-09-22','2026-09-23','2026-09-29','2026-10-13','2026-11-06',240),
('Biology','Structural Organisation in Animals and Plants',2,7,'Structural Organisation in Animals','2026-09-23','2026-09-24','2026-09-25','2026-10-01','2026-10-15','2026-11-08',240),
('Biology','Cell Structure and Function',3,8,'Cell: The Unit of Life','2026-09-26','2026-09-28','2026-09-29','2026-10-05','2026-10-19','2026-11-12',240),
('Biology','Cell Structure and Function',3,9,'Biomolecules','2026-09-29','2026-10-01','2026-10-02','2026-10-08','2026-10-22','2026-11-15',240),
('Biology','Cell Structure and Function',3,10,'Cell Cycle and Cell Division','2026-10-02','2026-10-03','2026-10-04','2026-10-10','2026-10-24','2026-11-17',240),
('Biology','Plant Physiology',4,11,'Photosynthesis in Higher Plants','2026-10-05','2026-10-07','2026-10-08','2026-10-14','2026-10-28','2026-11-21',240),
('Biology','Plant Physiology',4,12,'Respiration in Plants','2026-10-08','2026-10-10','2026-10-11','2026-10-17','2026-10-31','2026-11-24',240),
('Biology','Plant Physiology',4,13,'Plant Growth and Development','2026-10-11','2026-10-12','2026-10-13','2026-10-19','2026-11-02','2026-11-26',240),
('Biology','Human Physiology',5,14,'Breathing and Exchange of Gases','2026-10-14','2026-10-15','2026-10-16','2026-10-22','2026-11-05','2026-11-29',240),
('Biology','Human Physiology',5,15,'Body Fluids and Circulation','2026-10-16','2026-10-18','2026-10-19','2026-10-25','2026-11-08','2026-12-02',240),
('Biology','Human Physiology',5,16,'Excretory Products and their Elimination','2026-10-19','2026-10-21','2026-10-22','2026-10-28','2026-11-11','2026-12-05',240),
('Biology','Human Physiology',5,17,'Locomotion and Movement','2026-10-22','2026-10-23','2026-10-24','2026-10-30','2026-11-13','2026-12-07',240),
('Biology','Human Physiology',5,18,'Neural Control and Coordination','2026-10-24','2026-10-26','2026-10-27','2026-11-02','2026-11-16','2026-12-10',240),
('Biology','Human Physiology',5,19,'Chemical Coordination and Integration','2026-10-27','2026-10-29','2026-10-30','2026-11-05','2026-11-19','2026-12-13',240),
('Biology','Reproduction',6,20,'Sexual Reproduction in Flowering Plants','2026-11-01','2026-11-03','2026-11-04','2026-11-10','2026-11-24','2026-12-18',240),
('Biology','Reproduction',6,21,'Human Reproduction','2026-11-04','2026-11-06','2026-11-07','2026-11-13','2026-11-27','2026-12-21',240),
('Biology','Reproduction',6,22,'Reproductive Health','2026-11-07','2026-11-08','2026-11-09','2026-11-15','2026-11-29','2026-12-23',240),
('Biology','Genetics and Evolution',7,23,'Principles of Inheritance and Variation','2026-11-10','2026-11-13','2026-11-14','2026-11-20','2026-12-04','2026-12-28',240),
('Biology','Genetics and Evolution',7,24,'Molecular Basis of Inheritance','2026-11-14','2026-11-18','2026-11-19','2026-11-25','2026-12-09','2027-01-02',240),
('Biology','Genetics and Evolution',7,25,'Evolution','2026-11-19','2026-11-21','2026-11-22','2026-11-28','2026-12-12','2027-01-05',240),
('Biology','Biology and Human Welfare',8,26,'Human Health and Disease','2026-11-24','2026-11-26','2026-11-27','2026-12-03','2026-12-17','2027-01-10',240),
('Biology','Biology and Human Welfare',8,27,'Microbes in Human Welfare','2026-11-27','2026-11-28','2026-11-29','2026-12-05','2026-12-19','2027-01-12',240),
('Biology','Biotechnology and Its Applications',9,28,'Biotechnology: Principles and Processes','2026-11-30','2026-12-01','2026-12-02','2026-12-08','2026-12-22','2027-01-15',240),
('Biology','Biotechnology and Its Applications',9,29,'Biotechnology and Its Applications','2026-12-02','2026-12-03','2026-12-04','2026-12-10','2026-12-24','2027-01-17',240),
('Biology','Ecology and Environment',10,30,'Organisms and Populations','2026-12-05','2026-12-06','2026-12-07','2026-12-13','2026-12-27','2027-01-20',240),
('Biology','Ecology and Environment',10,31,'Ecosystem','2026-12-07','2026-12-08','2026-12-09','2026-12-15','2026-12-29','2027-01-22',240),
('Biology','Ecology and Environment',10,32,'Biodiversity and Conservation','2026-12-09','2026-12-10','2026-12-11','2026-12-17','2026-12-31','2027-01-24',240),
('Chemistry','Physical Chemistry',1,1,'Some Basic Concepts in Chemistry','2026-09-07','2026-09-09','2026-09-10','2026-09-16','2026-09-30','2026-10-24',240),
('Chemistry','Physical Chemistry',2,2,'Atomic Structure','2026-09-10','2026-09-13','2026-09-14','2026-09-20','2026-10-04','2026-10-28',240),
('Chemistry','Physical Chemistry',3,3,'Chemical Bonding and Molecular Structure','2026-09-14','2026-09-18','2026-09-19','2026-09-25','2026-10-09','2026-11-02',240),
('Chemistry','Physical Chemistry',4,4,'Chemical Thermodynamics','2026-09-19','2026-09-23','2026-09-24','2026-09-30','2026-10-14','2026-11-07',240),
('Chemistry','Physical Chemistry',5,5,'Solutions','2026-09-24','2026-09-27','2026-09-28','2026-10-04','2026-10-18','2026-11-11',240),
('Chemistry','Physical Chemistry',6,6,'Equilibrium','2026-09-28','2026-10-03','2026-10-04','2026-10-10','2026-10-24','2026-11-17',240),
('Chemistry','Physical Chemistry',7,7,'Redox Reactions and Electrochemistry','2026-10-04','2026-10-09','2026-10-10','2026-10-16','2026-10-30','2026-11-23',240),
('Chemistry','Physical Chemistry',8,8,'Chemical Kinetics','2026-10-10','2026-10-12','2026-10-13','2026-10-19','2026-11-02','2026-11-26',240),
('Chemistry','Inorganic Chemistry',9,9,'Classification of Elements and Periodicity in Properties','2026-10-15','2026-10-17','2026-10-18','2026-10-24','2026-11-07','2026-12-01',240),
('Chemistry','Inorganic Chemistry',10,10,'P-Block Elements','2026-10-18','2026-10-21','2026-10-22','2026-10-28','2026-11-11','2026-12-05',240),
('Chemistry','Inorganic Chemistry',11,11,'d- and f-Block Elements','2026-10-22','2026-10-25','2026-10-26','2026-11-01','2026-11-15','2026-12-09',240),
('Chemistry','Inorganic Chemistry',12,12,'Co-ordination Compounds','2026-10-26','2026-10-30','2026-10-31','2026-11-06','2026-11-20','2026-12-14',240),
('Chemistry','Organic Chemistry + Practical Application',13,13,'Purification and Characterisation of Organic Compounds','2026-11-01','2026-11-03','2026-11-04','2026-11-10','2026-11-24','2026-12-18',240),
('Chemistry','Organic Chemistry + Practical Application',14,14,'Some Basic Principles of Organic Chemistry','2026-11-04','2026-11-08','2026-11-09','2026-11-15','2026-11-29','2026-12-23',240),
('Chemistry','Organic Chemistry + Practical Application',15,15,'Hydrocarbons','2026-11-09','2026-11-13','2026-11-14','2026-11-20','2026-12-04','2026-12-28',240),
('Chemistry','Organic Chemistry + Practical Application',16,16,'Organic Compounds Containing Halogens','2026-11-14','2026-11-16','2026-11-17','2026-11-23','2026-12-07','2026-12-31',240),
('Chemistry','Organic Chemistry + Practical Application',17,17,'Organic Compounds Containing Oxygen','2026-11-17','2026-11-22','2026-11-23','2026-11-29','2026-12-13','2027-01-06',240),
('Chemistry','Organic Chemistry + Practical Application',18,18,'Organic Compounds Containing Nitrogen','2026-11-23','2026-11-25','2026-11-26','2026-12-02','2026-12-16','2027-01-09',240),
('Chemistry','Organic Chemistry + Practical Application',19,19,'Biomolecules','2026-11-26','2026-11-27','2026-11-28','2026-12-04','2026-12-18','2027-01-11',240),
('Chemistry','Organic Chemistry + Practical Application',20,20,'Principles Related to Practical Chemistry','2026-11-28','2026-11-30','2026-12-01','2026-12-07','2026-12-21','2027-01-14',240),
('Physics','Mechanics & Measurement',1,1,'Physics and Measurement','2026-09-07','2026-09-08','2026-09-09','2026-09-15','2026-09-29','2026-10-23',240),
('Physics','Mechanics & Measurement',2,2,'Kinematics','2026-09-09','2026-09-13','2026-09-14','2026-09-20','2026-10-04','2026-10-28',240),
('Physics','Mechanics & Measurement',3,3,'Laws of Motion','2026-09-14','2026-09-17','2026-09-18','2026-09-24','2026-10-08','2026-11-01',240),
('Physics','Mechanics & Measurement',4,4,'Work, Energy, and Power','2026-09-18','2026-09-21','2026-09-22','2026-09-28','2026-10-12','2026-11-05',240),
('Physics','Mechanics & Measurement',5,5,'Rotational Motion','2026-09-22','2026-09-27','2026-09-28','2026-10-04','2026-10-18','2026-11-11',240),
('Physics','Mechanics & Measurement',6,6,'Gravitation','2026-09-28','2026-09-30','2026-10-01','2026-10-07','2026-10-21','2026-11-14',240),
('Physics','Properties & Thermal Physics',7,7,'Properties of Solids and Liquids','2026-10-03','2026-10-08','2026-10-09','2026-10-15','2026-10-29','2026-11-22',240),
('Physics','Properties & Thermal Physics',8,8,'Thermodynamics','2026-10-09','2026-10-11','2026-10-12','2026-10-18','2026-11-01','2026-11-25',240),
('Physics','Properties & Thermal Physics',9,9,'Kinetic Theory of Gases','2026-10-12','2026-10-13','2026-10-14','2026-10-20','2026-11-03','2026-11-27',240),
('Physics','Oscillations & Waves',10,10,'Oscillations and Waves','2026-10-15','2026-10-19','2026-10-20','2026-10-26','2026-11-09','2026-12-03',240),
('Physics','Electricity & Magnetism',11,11,'Electrostatics','2026-10-21','2026-10-26','2026-10-27','2026-11-02','2026-11-16','2026-12-10',240),
('Physics','Electricity & Magnetism',12,12,'Current Electricity','2026-10-27','2026-10-31','2026-11-01','2026-11-07','2026-11-21','2026-12-15',240),
('Physics','Electricity & Magnetism',13,13,'Magnetic Effects of Current and Magnetism','2026-11-01','2026-11-05','2026-11-06','2026-11-12','2026-11-26','2026-12-20',240),
('Physics','Electricity & Magnetism',14,14,'Electromagnetic Induction and Alternating Currents','2026-11-06','2026-11-09','2026-11-10','2026-11-16','2026-11-30','2026-12-24',240),
('Physics','Electricity & Magnetism',15,15,'Electromagnetic Waves','2026-11-10','2026-11-10','2026-11-11','2026-11-17','2026-12-01','2026-12-25',240),
('Physics','Optics',16,16,'Optics','2026-11-13','2026-11-18','2026-11-19','2026-11-25','2026-12-09','2027-01-02',240),
('Physics','Modern Physics & Electronics',17,17,'Dual Nature of Matter and Radiation','2026-11-20','2026-11-21','2026-11-22','2026-11-28','2026-12-12','2027-01-05',240),
('Physics','Modern Physics & Electronics',18,18,'Atoms and Nuclei','2026-11-22','2026-11-24','2026-11-25','2026-12-01','2026-12-15','2027-01-08',240),
('Physics','Modern Physics & Electronics',19,19,'Electronic Devices','2026-11-25','2026-11-26','2026-11-27','2026-12-03','2026-12-17','2027-01-10',240),
('Physics','Experimental Skills',20,20,'Experimental Skills','2026-11-28','2026-11-30','2026-12-01','2026-12-07','2026-12-21','2027-01-14',240)
on conflict (subject,chapter_no) do update set
  plan_group=excluded.plan_group, unit_no=excluded.unit_no, chapter=excluded.chapter,
  study_start=excluded.study_start, study_end=excluded.study_end,
  r1_date=excluded.r1_date, r2_date=excluded.r2_date, r3_date=excluded.r3_date, r4_date=excluded.r4_date,
  planned_minutes=excluded.planned_minutes, updated_at=now();

create or replace view public.academy_daily_study_plan with (security_invoker = true) as
select d::date plan_date,c.subject,c.plan_group,c.unit_no,c.chapter_no,c.chapter,'study'::text event_type,
       (d::date-c.study_start+1)::integer day_no,(c.study_end-c.study_start+1)::integer total_days,
       null::text revision_stage,c.planned_minutes
from public.academy_study_plan_chapters c
cross join lateral generate_series(c.study_start::timestamp,c.study_end::timestamp,interval '1 day') d
union all select c.r1_date,c.subject,c.plan_group,c.unit_no,c.chapter_no,c.chapter,'revision',null,null,'R1',c.planned_minutes from public.academy_study_plan_chapters c
union all select c.r2_date,c.subject,c.plan_group,c.unit_no,c.chapter_no,c.chapter,'revision',null,null,'R2',c.planned_minutes from public.academy_study_plan_chapters c
union all select c.r3_date,c.subject,c.plan_group,c.unit_no,c.chapter_no,c.chapter,'revision',null,null,'R3',c.planned_minutes from public.academy_study_plan_chapters c
union all select c.r4_date,c.subject,c.plan_group,c.unit_no,c.chapter_no,c.chapter,'revision',null,null,'R4',c.planned_minutes from public.academy_study_plan_chapters c;

revoke all on public.academy_daily_study_plan from anon, authenticated;
grant select on public.academy_daily_study_plan to authenticated, service_role;
