(async()=>{
const c=window.sgaSupabase,rows=document.getElementById('rows'),modal=document.getElementById('modal'),search=document.getElementById('search'),scopeUtils=window.ExamScopeUIUtils;let exams=[];
const officialTemplates={daily:{label:'DAILY',questions:45,duration:45,marks:180},unit:{label:'UNIT',questions:180,duration:180,marks:720},monthly:{label:'MONTHLY',questions:180,duration:180,marks:720}};
const {data:{session}}=await c.auth.getSession();if(!session)return location.replace('admin-login.html');
const {data:me}=await c.from('profiles').select('role,is_active').eq('id',session.user.id).single();if(!me||me.role!=='admin'||!me.is_active){await c.auth.signOut();return location.replace('admin-login.html')}
const esc=v=>String(v??'').replace(/[&<>"']/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[ch]));
async function call(body){const {data:{session}}=await c.auth.getSession();const r=await fetch(`${window.SGA_SUPABASE_URL}/functions/v1/admin-exams`,{method:'POST',headers:{'Content-Type':'application/json','apikey':window.SGA_SUPABASE_PUBLISHABLE_KEY,'Authorization':`Bearer ${session.access_token}`},body:JSON.stringify(body)});const d=await r.json();if(!r.ok){const err=new Error(d.error||'Request failed');err.validation=d.validation||null;throw err}return d}
function examAccess(x){return Array.isArray(x.exam_access)?x.exam_access[0]:x.exam_access}
function publishError(err){const v=err?.validation;if(!v)return err?.message||'Publish failed.';const mapped=Number(v.mappedQuestions||0),total=Number(v.totalQuestions||0),details=(v.errors||[]).join(' ');return `Publish blocked — Mapped ${mapped}/${total}. ${details} Open QUESTIONS → Syllabus Range Mapping to correct it.`.replace(/\s+/g,' ').trim()}
function dateLabel(v){if(!v)return '—';const d=new Date(`${v}T00:00:00`);return Number.isNaN(d.getTime())?esc(v):d.toLocaleDateString('en-IN',{day:'2-digit',month:'short',year:'numeric'})}
function examTypeLabel(x){return x.exam_type?officialTemplates[x.exam_type]?.label||String(x.exam_type).toUpperCase():'LEGACY'}
function render(){const q=search.value.trim().toLowerCase();const list=exams.filter(x=>!q||[x.title,x.subject,x.exam_type,x.exam_date,examAccess(x)?.exam_code].some(v=>String(v||'').toLowerCase().includes(q)));document.getElementById('countLine').textContent=`${list.length} exam${list.length===1?'':'s'} shown`;
rows.innerHTML=list.length?list.map(x=>{const code=examAccess(x)?.exam_code||'—',mode=(x.audience_mode||'all').toUpperCase();return `<tr><td><strong>${esc(x.title)}</strong><br><small>${esc(x.syllabus||'')}</small><br><span class="type-badge">${esc(examTypeLabel(x))}</span></td><td>${dateLabel(x.exam_date)}</td><td>${esc(x.subject)}</td><td><strong>${esc(code)}</strong></td><td>${esc(x.duration_minutes)} min</td><td>${esc(x.total_marks)}</td><td><span class="badge ${x.is_published?'published':'draft'}">${x.is_published?'PUBLISHED':'DRAFT'}</span><br><small>${x.is_published?mode+' STUDENTS':'—'}</small></td><td><button class="small-btn edit" data-id="${x.id}">EDIT</button><button class="small-btn questions" data-id="${x.id}">QUESTIONS</button>${x.is_published?`<button class="small-btn audience" data-id="${x.id}">AUDIENCE</button><button class="small-btn pub" data-id="${x.id}" data-pub="true">UNPUBLISH</button>`:`<button class="small-btn audience" data-id="${x.id}" data-publish="true">PUBLISH</button>`}<button class="small-btn manage" data-id="${x.id}">RE-EXAM / RESET</button><button class="small-btn danger del" data-id="${x.id}">DELETE</button></td></tr>`}).join(''):`<tr><td colspan="8">No exams created yet.</td></tr>`}
async function load(){const {data,error}=await c.from('exams').select('id,title,subject,syllabus,exam_type,exam_date,expected_questions,duration_minutes,total_marks,negative_marking,instructions,status,is_published,audience_mode,exam_access(exam_code)').order('created_at',{ascending:false});if(error){rows.innerHTML=`<tr><td colspan="8">Unable to load exams. ${esc(error.message)}</td></tr>`;return}exams=data||[];render()}
search.oninput=render;

let scopeTree=[],scopeDraft=[],scopeTreeError='';
const scopeRows=document.getElementById('scopeRows'),legacyScopeNote=document.getElementById('legacyScopeNote');
const subjectOptions=['Physics','Chemistry','Biology'];
function option(value,label,selected){return `<option value="${esc(value)}" ${String(value)===String(selected)?'selected':''}>${esc(label)}</option>`}
function defaultScopeSubject(){const s=document.getElementById('subject').value;return subjectOptions.includes(s)?s:''}
function addScopeDraft(seed={}){scopeDraft.push({subject:seed.subject||defaultScopeSubject(),unitId:seed.unitId||'',chapterId:seed.chapterId||'',subtopicId:seed.subtopicId??''});renderScopeRows()}
function renderScopeRows(){if(!scopeDraft.length){scopeRows.innerHTML='<div class="scope-empty">No structured scope rows. Add one to define official exam coverage.</div>';return}
scopeRows.innerHTML=scopeDraft.map((row,i)=>{const units=scopeUtils.unitsForSubject(scopeTree,row.subject),chapters=scopeUtils.chaptersForUnit(scopeTree,row.unitId),subs=scopeUtils.approvedSubtopicsForChapter(scopeTree,row.chapterId);return `<div class="scope-row" data-i="${i}"><div><label>Subject</label><select class="scope-subject"><option value="">Select Subject</option>${subjectOptions.map(s=>option(s,s,row.subject)).join('')}</select></div><div><label>Unit</label><select class="scope-unit"><option value="">Select Unit</option>${units.map(u=>option(u.id,`${u.unit_no?`Unit ${u.unit_no}: `:''}${u.unit_title}`,row.unitId)).join('')}</select></div><div><label>Chapter</label><select class="scope-chapter"><option value="">Select Chapter</option>${chapters.map(ch=>option(ch.id,ch.topic_title,row.chapterId)).join('')}</select></div><div><label>Topic/Subtopic</label><select class="scope-subtopic"><option value="">Whole Chapter / No specific topic</option>${subs.map(st=>option(st.id,st.subtopic_title,row.subtopicId)).join('')}</select></div><button type="button" class="scope-remove">REMOVE</button></div>`}).join('')}
scopeRows.onchange=e=>{const rowEl=e.target.closest('.scope-row');if(!rowEl)return;const i=Number(rowEl.dataset.i),row=scopeDraft[i];if(e.target.classList.contains('scope-subject')){row.subject=e.target.value;row.unitId='';row.chapterId='';row.subtopicId=''}else if(e.target.classList.contains('scope-unit')){row.unitId=e.target.value;row.chapterId='';row.subtopicId=''}else if(e.target.classList.contains('scope-chapter')){row.chapterId=e.target.value;row.subtopicId=''}else if(e.target.classList.contains('scope-subtopic'))row.subtopicId=e.target.value;renderScopeRows()};
scopeRows.onclick=e=>{const btn=e.target.closest('.scope-remove');if(!btn)return;const i=Number(btn.closest('.scope-row').dataset.i);scopeDraft.splice(i,1);renderScopeRows()};
document.getElementById('addScopeRow').onclick=()=>addScopeDraft();
document.getElementById('subject').onchange=()=>{const forced=defaultScopeSubject();if(forced){for(const row of scopeDraft){if(!row.subject){row.subject=forced;row.unitId='';row.chapterId='';row.subtopicId=''}}renderScopeRows()}};
async function loadScopeTreeOnce(){try{const d=await call({action:'scope_tree'});scopeTree=d.syllabus||[];scopeTreeError='';renderScopeRows()}catch(e){scopeTreeError=e.message||'Unable to load syllabus';scopeRows.innerHTML=`<div class="scope-empty">${esc(scopeTreeError)}</div>`}}
function draftFromSaved(items){return (items||[]).map(item=>{const unit=scopeTree.find(u=>String(u.id)===String(item.unitId));return{subject:unit?.subject||'',unitId:item.unitId||'',chapterId:item.chapterId||'',subtopicId:item.subtopicId??''}})}
function localToday(){const d=new Date(),local=new Date(d.getTime()-d.getTimezoneOffset()*60000);return local.toISOString().slice(0,10)}
function applyExamTemplate(){const type=document.getElementById('examType').value,t=officialTemplates[type];if(!t)return;document.getElementById('expectedQuestions').value=t.questions;document.getElementById('duration').value=t.duration;document.getElementById('marks').value=t.marks;document.getElementById('negative').checked=true;document.getElementById('templateQuestions').textContent=t.questions;document.getElementById('templateDuration').textContent=`${t.duration} min`;document.getElementById('templateMarks').textContent=t.marks;const subject=document.getElementById('subject');if(type==='unit'||type==='monthly'){subject.value='NEET';subject.disabled=true}else subject.disabled=false}

let editingExamId=null,editingLegacyWithoutScope=false,editingOfficial=false;
const form=document.getElementById('examForm'),formTitle=document.getElementById('examFormTitle'),saveBtn=document.getElementById('createBtn');
function resetExamForm(){editingExamId=null;editingLegacyWithoutScope=false;editingOfficial=false;form.reset();document.getElementById('examType').disabled=false;document.getElementById('examType').value='daily';document.getElementById('examDate').disabled=false;document.getElementById('examDate').required=true;document.getElementById('examDate').value=localToday();document.getElementById('duration').readOnly=true;document.getElementById('marks').readOnly=true;document.getElementById('expectedQuestions').readOnly=true;document.getElementById('code').readOnly=true;document.getElementById('code').value='';document.getElementById('code').placeholder='Generated automatically after save';document.getElementById('negative').disabled=true;document.getElementById('negative').checked=true;document.getElementById('password').required=true;document.getElementById('password').placeholder='Minimum 4 characters';document.getElementById('subject').disabled=false;applyExamTemplate();formTitle.textContent='Create New Exam';saveBtn.textContent='CREATE EXAM';document.getElementById('formMsg').textContent='';legacyScopeNote.style.display='none';legacyScopeNote.textContent='';scopeDraft=[];addScopeDraft()}
document.getElementById('examType').onchange=applyExamTemplate;
document.getElementById('addBtn').onclick=()=>{resetExamForm();modal.classList.add('open')};document.getElementById('cancel').onclick=()=>{modal.classList.remove('open');resetExamForm()};
form.onsubmit=async e=>{e.preventDefault();const wasEditing=Boolean(editingExamId),msg=document.getElementById('formMsg'),btn=saveBtn;if(scopeTreeError){msg.textContent=scopeTreeError;return}const norm=scopeUtils.normaliseScopeDraft(scopeDraft);if(!norm.ok){msg.textContent=norm.error;return}if(!wasEditing&&!norm.items.length){msg.textContent='Add at least one syllabus scope row.';return}btn.disabled=true;btn.textContent=wasEditing?'UPDATING...':'CREATING...';msg.textContent=wasEditing?'Updating exam...':'Creating exam...';try{const saved=await call({action:wasEditing?'update':'create',examId:editingExamId||undefined,title:document.getElementById('title').value.trim(),subject:document.getElementById('subject').value,scopeItems:norm.items,examType:document.getElementById('examType').value,examDate:document.getElementById('examDate').value,durationMinutes:Number(document.getElementById('duration').value),totalMarks:Number(document.getElementById('marks').value),legacyExamCode:wasEditing&&!editingOfficial?document.getElementById('code').value.trim():undefined,examPassword:document.getElementById('password').value,instructions:document.getElementById('instructions').value.trim(),negativeMarking:document.getElementById('negative').checked});modal.classList.remove('open');resetExamForm();await load();alert(wasEditing?'Exam updated successfully.':`Exam created as Draft.\nExam Code: ${saved.examCode||'Generated'}\nAdd questions before publishing.`)}catch(err){msg.textContent=err.message}finally{btn.disabled=false;btn.textContent=wasEditing?'UPDATE EXAM':'CREATE EXAM'}};

let audienceExamId=null,audienceWillPublish=false,audienceData=null;
const audienceModal=document.getElementById('audienceModal'),audienceStudents=document.getElementById('audienceStudents'),audienceMsg=document.getElementById('audienceMsg');
function drawAudience(){if(!audienceData)return;const mode=document.querySelector('input[name="audienceMode"]:checked')?.value||'all';audienceStudents.innerHTML=audienceData.students.map(s=>`<label class="student-row"><input class="aud-check" type="checkbox" value="${s.id}" ${s.assigned?'checked':''} ${mode==='all'?'disabled':''}><span><b>${esc(s.full_name||'Student')}</b><br><small>${esc(s.student_id||'—')}</small></span><small>${s.max_attempts>1?`Allowed ${s.max_attempts} attempts`:''}</small></label>`).join('')||'<div class="student-row">No active students.</div>';audienceMsg.textContent=mode==='all'?`All ${audienceData.students.length} active students will have access.`:'Only checked students will have access.'}
async function openAudience(id,willPublish){audienceExamId=id;audienceWillPublish=willPublish;audienceMsg.textContent='Loading students...';audienceModal.classList.add('open');try{audienceData=await call({action:'students',examId:id});const mode=audienceData.audienceMode||'all';const radio=document.querySelector(`input[name="audienceMode"][value="${mode}"]`);if(radio)radio.checked=true;document.getElementById('audienceTitle').textContent=willPublish?'Publish Exam':'Manage Exam Audience';document.getElementById('audienceSave').textContent=willPublish?'SAVE & PUBLISH':'SAVE AUDIENCE';drawAudience()}catch(e){audienceMsg.textContent=e.message}}
document.querySelectorAll('input[name="audienceMode"]').forEach(r=>r.onchange=drawAudience);document.getElementById('audienceCancel').onclick=()=>audienceModal.classList.remove('open');document.getElementById('audienceSave').onclick=async()=>{const btn=document.getElementById('audienceSave'),mode=document.querySelector('input[name="audienceMode"]:checked')?.value||'all',studentIds=mode==='selected'?[...document.querySelectorAll('.aud-check:checked')].map(x=>x.value):[];btn.disabled=true;audienceMsg.textContent='Saving audience...';try{await call({action:audienceWillPublish?'publish':'set_audience',examId:audienceExamId,audienceMode:mode,studentIds});audienceModal.classList.remove('open');await load()}catch(e){audienceMsg.textContent=audienceWillPublish?publishError(e):e.message}finally{btn.disabled=false}};

let maintenanceExamId=null,maintenanceData=null;const maintenanceModal=document.getElementById('maintenanceModal'),maintMsg=document.getElementById('maintenanceMsg'),maintStudent=document.getElementById('maintStudent');
async function openMaintenance(id){maintenanceExamId=id;maintMsg.textContent='Loading students...';maintenanceModal.classList.add('open');try{maintenanceData=await call({action:'students',examId:id});const eligible=maintenanceData.audienceMode==='all'?maintenanceData.students:maintenanceData.students.filter(s=>s.assigned);maintStudent.innerHTML=eligible.map(s=>`<option value="${s.id}">${esc(s.full_name)} (${esc(s.student_id||'—')}) — max ${s.max_attempts}</option>`).join('');maintMsg.textContent=eligible.length?'Choose selected or all assigned students.':'No assigned students found.'}catch(e){maintMsg.textContent=e.message}}
document.getElementById('maintenanceClose').onclick=()=>maintenanceModal.classList.remove('open');
async function maintAction(action,confirmText){const studentId=maintStudent.value;if(action.endsWith('_student')&&!studentId)return alert('Select a student.');if(confirmText&&!confirm(confirmText))return;maintMsg.textContent='Processing...';try{const body={action,examId:maintenanceExamId};if(action.endsWith('_student'))body.studentId=studentId;const d=await call(body);maintMsg.textContent=action.startsWith('reexam')?`Re-exam permission updated${d.affected?` for ${d.affected} students`:''}.`:'Reset completed.';maintenanceData=await call({action:'students',examId:maintenanceExamId});const eligible=maintenanceData.audienceMode==='all'?maintenanceData.students:maintenanceData.students.filter(s=>s.assigned);maintStudent.innerHTML=eligible.map(s=>`<option value="${s.id}">${esc(s.full_name)} (${esc(s.student_id||'—')}) — max ${s.max_attempts}</option>`).join('')}catch(e){maintMsg.textContent=e.message}}
document.getElementById('reexamStudent').onclick=()=>maintAction('reexam_student','Grant one additional attempt to this student? Previous valid result will be kept.');document.getElementById('reexamAll').onclick=()=>maintAction('reexam_all','Grant one additional attempt to ALL assigned students? Previous valid results will be kept.');document.getElementById('resetStudent').onclick=()=>maintAction('reset_student','RESET this student? All attempts/results for this exam will be deleted for this student.');document.getElementById('resetAll').onclick=()=>maintAction('reset_all','RESET ALL students for this exam? All attempts, responses and results for this exam will be deleted.');

async function openEdit(x){editingExamId=x.id;editingLegacyWithoutScope=false;editingOfficial=Boolean(x.exam_type);formTitle.textContent='Edit Exam';saveBtn.textContent='UPDATE EXAM';document.getElementById('title').value=x.title||'';document.getElementById('subject').value=x.subject||'NEET';document.getElementById('duration').value=x.duration_minutes||180;document.getElementById('marks').value=x.total_marks||720;document.getElementById('expectedQuestions').value=x.expected_questions||'';document.getElementById('code').value=examAccess(x)?.exam_code||'';document.getElementById('password').value='';document.getElementById('password').required=false;document.getElementById('password').placeholder='Leave blank to keep current password';document.getElementById('instructions').value=x.instructions||'';document.getElementById('negative').checked=!!x.negative_marking;document.getElementById('formMsg').textContent='Loading syllabus scope...';legacyScopeNote.style.display='none';scopeDraft=[];renderScopeRows();if(editingOfficial){document.getElementById('examType').value=x.exam_type;document.getElementById('examDate').value=x.exam_date||'';document.getElementById('examType').disabled=true;document.getElementById('examDate').disabled=true;document.getElementById('duration').readOnly=true;document.getElementById('marks').readOnly=true;document.getElementById('code').readOnly=true;document.getElementById('negative').disabled=true;applyExamTemplate()}else{document.getElementById('examType').value='legacy';document.getElementById('examType').disabled=true;document.getElementById('examDate').value='';document.getElementById('examDate').required=false;document.getElementById('examDate').disabled=true;document.getElementById('duration').readOnly=false;document.getElementById('marks').readOnly=false;document.getElementById('code').readOnly=false;document.getElementById('negative').disabled=false;document.getElementById('subject').disabled=false;document.getElementById('templateQuestions').textContent=x.expected_questions||'—';document.getElementById('templateDuration').textContent=`${x.duration_minutes||'—'} min`;document.getElementById('templateMarks').textContent=x.total_marks||'—'}modal.classList.add('open');try{const d=await call({action:'get_scope',examId:x.id});scopeDraft=draftFromSaved(d.scopeItems||[]);editingLegacyWithoutScope=!scopeDraft.length;if(editingLegacyWithoutScope&&d.legacySyllabus){legacyScopeNote.style.display='block';legacyScopeNote.textContent=`Legacy syllabus: ${d.legacySyllabus}. No structured scope has been guessed. Add scope rows when you are ready.`}renderScopeRows();document.getElementById('formMsg').textContent=''}catch(e){document.getElementById('formMsg').textContent=e.message}}
rows.onclick=async e=>{const edit=e.target.closest('.edit'),questions=e.target.closest('.questions'),pub=e.target.closest('.pub'),aud=e.target.closest('.audience'),manage=e.target.closest('.manage'),del=e.target.closest('.del');if(edit){const x=exams.find(v=>v.id===edit.dataset.id);if(x)await openEdit(x);return}if(questions){location.href=`admin-exam-questions.html?exam=${encodeURIComponent(questions.dataset.id)}`;return}if(aud){openAudience(aud.dataset.id,aud.dataset.publish==='true');return}if(manage){openMaintenance(manage.dataset.id);return}if(pub){if(!confirm('Unpublish this exam? Students will no longer be able to start it.'))return;pub.disabled=true;try{await call({action:'unpublish',examId:pub.dataset.id});await load()}catch(err){alert(err.message)}return}if(del){const x=exams.find(v=>v.id===del.dataset.id);if(!x)return;const code=examAccess(x)?.exam_code||'';const typed=prompt(`DELETE EXAM COMPLETELY\n\nThis removes questions, attempts, responses and results.\nType Exam Code ${code} to confirm:`);if(typed===null)return;try{await call({action:'delete',examId:x.id,confirmCode:typed});await load()}catch(err){alert(err.message)}}};
document.getElementById('logout').onclick=async()=>{await c.auth.signOut();location.replace('admin-login.html')};
await loadScopeTreeOnce();resetExamForm();await load();
})();