(async()=>{
const c=window.sgaSupabase,rows=document.getElementById('rows'),modal=document.getElementById('modal'),search=document.getElementById('search');let exams=[];
const {data:{session}}=await c.auth.getSession();if(!session)return location.replace('admin-login.html');
const {data:me}=await c.from('profiles').select('role,is_active').eq('id',session.user.id).single();if(!me||me.role!=='admin'||!me.is_active){await c.auth.signOut();return location.replace('admin-login.html')}
const esc=v=>String(v??'').replace(/[&<>"']/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[ch]));
async function call(body){const {data:{session}}=await c.auth.getSession();const r=await fetch(`${window.SGA_SUPABASE_URL}/functions/v1/admin-exams`,{method:'POST',headers:{'Content-Type':'application/json','apikey':window.SGA_SUPABASE_PUBLISHABLE_KEY,'Authorization':`Bearer ${session.access_token}`},body:JSON.stringify(body)});const d=await r.json();if(!r.ok){const err=new Error(d.error||'Request failed');err.validation=d.validation||null;throw err}return d}
function examAccess(x){return Array.isArray(x.exam_access)?x.exam_access[0]:x.exam_access}
function publishError(err){const v=err?.validation;if(!v)return err?.message||'Publish failed.';const mapped=Number(v.mappedQuestions||0),total=Number(v.totalQuestions||0),details=(v.errors||[]).join(' ');return `Publish blocked — Mapped ${mapped}/${total}. ${details} Open QUESTIONS → Syllabus Range Mapping to correct it.`.replace(/\s+/g,' ').trim()}
function render(){const q=search.value.trim().toLowerCase();const list=exams.filter(x=>!q||[x.title,x.subject,examAccess(x)?.exam_code].some(v=>String(v||'').toLowerCase().includes(q)));document.getElementById('countLine').textContent=`${list.length} exam${list.length===1?'':'s'} shown`;
rows.innerHTML=list.length?list.map(x=>{const code=examAccess(x)?.exam_code||'—',mode=(x.audience_mode||'all').toUpperCase();return `<tr><td><strong>${esc(x.title)}</strong><br><small>${esc(x.syllabus||'')}</small></td><td>${esc(x.subject)}</td><td><strong>${esc(code)}</strong></td><td>${esc(x.duration_minutes)} min</td><td>${esc(x.total_marks)}</td><td><span class="badge ${x.is_published?'published':'draft'}">${x.is_published?'PUBLISHED':'DRAFT'}</span><br><small>${x.is_published?mode+' STUDENTS':'—'}</small></td><td><button class="small-btn edit" data-id="${x.id}">EDIT</button><button class="small-btn questions" data-id="${x.id}">QUESTIONS</button>${x.is_published?`<button class="small-btn audience" data-id="${x.id}">AUDIENCE</button><button class="small-btn pub" data-id="${x.id}" data-pub="true">UNPUBLISH</button>`:`<button class="small-btn audience" data-id="${x.id}" data-publish="true">PUBLISH</button>`}<button class="small-btn manage" data-id="${x.id}">RE-EXAM / RESET</button><button class="small-btn danger del" data-id="${x.id}">DELETE</button></td></tr>`}).join(''):`<tr><td colspan="7">No exams created yet.</td></tr>`}
async function load(){const {data,error}=await c.from('exams').select('id,title,subject,syllabus,duration_minutes,total_marks,negative_marking,instructions,status,is_published,audience_mode,exam_access(exam_code)').order('created_at',{ascending:false});if(error){rows.innerHTML=`<tr><td colspan="7">Unable to load exams. ${esc(error.message)}</td></tr>`;return}exams=data||[];render()}
search.oninput=render;
let editingExamId=null;
const form=document.getElementById('examForm'),formTitle=document.getElementById('examFormTitle'),saveBtn=document.getElementById('createBtn');
function resetExamForm(){editingExamId=null;form.reset();document.getElementById('duration').value=180;document.getElementById('marks').value=720;document.getElementById('negative').checked=true;document.getElementById('password').required=true;document.getElementById('password').placeholder='Minimum 4 characters';formTitle.textContent='Create New Exam';saveBtn.textContent='CREATE EXAM';document.getElementById('formMsg').textContent=''}
document.getElementById('addBtn').onclick=()=>{resetExamForm();modal.classList.add('open')};document.getElementById('cancel').onclick=()=>{modal.classList.remove('open');resetExamForm()};document.getElementById('code').oninput=e=>e.target.value=e.target.value.toUpperCase().replace(/[^A-Z0-9-]/g,'').slice(0,20);
form.onsubmit=async e=>{e.preventDefault();const wasEditing=Boolean(editingExamId),msg=document.getElementById('formMsg'),btn=saveBtn;btn.disabled=true;btn.textContent=wasEditing?'UPDATING...':'CREATING...';msg.textContent=wasEditing?'Updating exam...':'Creating exam...';try{await call({action:wasEditing?'update':'create',examId:editingExamId||undefined,title:document.getElementById('title').value.trim(),subject:document.getElementById('subject').value,syllabus:document.getElementById('syllabus').value.trim(),durationMinutes:Number(document.getElementById('duration').value),totalMarks:Number(document.getElementById('marks').value),examCode:document.getElementById('code').value.trim(),examPassword:document.getElementById('password').value,instructions:document.getElementById('instructions').value.trim(),negativeMarking:document.getElementById('negative').checked});modal.classList.remove('open');resetExamForm();await load();alert(wasEditing?'Exam updated successfully.':'Exam created as Draft. Add questions before publishing.')}catch(err){msg.textContent=err.message}finally{btn.disabled=false;btn.textContent=editingExamId?'UPDATE EXAM':'CREATE EXAM'}};

let audienceExamId=null,audienceWillPublish=false,audienceData=null;
const audienceModal=document.getElementById('audienceModal'),audienceStudents=document.getElementById('audienceStudents'),audienceMsg=document.getElementById('audienceMsg');
function drawAudience(){if(!audienceData)return;const mode=document.querySelector('input[name="audienceMode"]:checked')?.value||'all';audienceStudents.innerHTML=audienceData.students.map(s=>`<label class="student-row"><input class="aud-check" type="checkbox" value="${s.id}" ${s.assigned?'checked':''} ${mode==='all'?'disabled':''}><span><b>${esc(s.full_name||'Student')}</b><br><small>${esc(s.student_id||'—')}</small></span><small>${s.max_attempts>1?`Allowed ${s.max_attempts} attempts`:''}</small></label>`).join('')||'<div class="student-row">No active students.</div>';audienceMsg.textContent=mode==='all'?`All ${audienceData.students.length} active students will have access.`:'Only checked students will have access.'}
async function openAudience(id,willPublish){audienceExamId=id;audienceWillPublish=willPublish;audienceMsg.textContent='Loading students...';audienceModal.classList.add('open');try{audienceData=await call({action:'students',examId:id});const mode=audienceData.audienceMode||'all';const radio=document.querySelector(`input[name="audienceMode"][value="${mode}"]`);if(radio)radio.checked=true;document.getElementById('audienceTitle').textContent=willPublish?'Publish Exam':'Manage Exam Audience';document.getElementById('audienceSave').textContent=willPublish?'SAVE & PUBLISH':'SAVE AUDIENCE';drawAudience()}catch(e){audienceMsg.textContent=e.message}}
document.querySelectorAll('input[name="audienceMode"]').forEach(r=>r.onchange=drawAudience);document.getElementById('audienceCancel').onclick=()=>audienceModal.classList.remove('open');document.getElementById('audienceSave').onclick=async()=>{const btn=document.getElementById('audienceSave'),mode=document.querySelector('input[name="audienceMode"]:checked')?.value||'all',studentIds=mode==='selected'?[...document.querySelectorAll('.aud-check:checked')].map(x=>x.value):[];btn.disabled=true;audienceMsg.textContent='Saving audience...';try{await call({action:audienceWillPublish?'publish':'set_audience',examId:audienceExamId,audienceMode:mode,studentIds});audienceModal.classList.remove('open');await load()}catch(e){audienceMsg.textContent=audienceWillPublish?publishError(e):e.message}finally{btn.disabled=false}};

let maintenanceExamId=null,maintenanceData=null;const maintenanceModal=document.getElementById('maintenanceModal'),maintMsg=document.getElementById('maintenanceMsg'),maintStudent=document.getElementById('maintStudent');
async function openMaintenance(id){maintenanceExamId=id;maintMsg.textContent='Loading students...';maintenanceModal.classList.add('open');try{maintenanceData=await call({action:'students',examId:id});const eligible=maintenanceData.audienceMode==='all'?maintenanceData.students:maintenanceData.students.filter(s=>s.assigned);maintStudent.innerHTML=eligible.map(s=>`<option value="${s.id}">${esc(s.full_name)} (${esc(s.student_id||'—')}) — max ${s.max_attempts}</option>`).join('');maintMsg.textContent=eligible.length?'Choose selected or all assigned students.':'No assigned students found.'}catch(e){maintMsg.textContent=e.message}}
document.getElementById('maintenanceClose').onclick=()=>maintenanceModal.classList.remove('open');
async function maintAction(action,confirmText){const studentId=maintStudent.value;if(action.endsWith('_student')&&!studentId)return alert('Select a student.');if(confirmText&&!confirm(confirmText))return;maintMsg.textContent='Processing...';try{const body={action,examId:maintenanceExamId};if(action.endsWith('_student'))body.studentId=studentId;const d=await call(body);maintMsg.textContent=action.startsWith('reexam')?`Re-exam permission updated${d.affected?` for ${d.affected} students`:''}.`:'Reset completed.';maintenanceData=await call({action:'students',examId:maintenanceExamId});const eligible=maintenanceData.audienceMode==='all'?maintenanceData.students:maintenanceData.students.filter(s=>s.assigned);maintStudent.innerHTML=eligible.map(s=>`<option value="${s.id}">${esc(s.full_name)} (${esc(s.student_id||'—')}) — max ${s.max_attempts}</option>`).join('')}catch(e){maintMsg.textContent=e.message}}
document.getElementById('reexamStudent').onclick=()=>maintAction('reexam_student','Grant one additional attempt to this student? Previous valid result will be kept.');document.getElementById('reexamAll').onclick=()=>maintAction('reexam_all','Grant one additional attempt to ALL assigned students? Previous valid results will be kept.');document.getElementById('resetStudent').onclick=()=>maintAction('reset_student','RESET this student? All attempts/results for this exam will be deleted for this student.');document.getElementById('resetAll').onclick=()=>maintAction('reset_all','RESET ALL students for this exam? All attempts, responses and results for this exam will be deleted.');

rows.onclick=async e=>{const edit=e.target.closest('.edit'),questions=e.target.closest('.questions'),pub=e.target.closest('.pub'),aud=e.target.closest('.audience'),manage=e.target.closest('.manage'),del=e.target.closest('.del');if(edit){const x=exams.find(v=>v.id===edit.dataset.id);if(!x)return;editingExamId=x.id;formTitle.textContent='Edit Exam';saveBtn.textContent='UPDATE EXAM';document.getElementById('title').value=x.title||'';document.getElementById('subject').value=x.subject||'NEET';document.getElementById('syllabus').value=x.syllabus||'';document.getElementById('duration').value=x.duration_minutes||180;document.getElementById('marks').value=x.total_marks||720;document.getElementById('code').value=examAccess(x)?.exam_code||'';document.getElementById('password').value='';document.getElementById('password').required=false;document.getElementById('password').placeholder='Leave blank to keep current password';document.getElementById('instructions').value=x.instructions||'';document.getElementById('negative').checked=!!x.negative_marking;modal.classList.add('open');return}if(questions){location.href=`admin-exam-questions.html?exam=${encodeURIComponent(questions.dataset.id)}`;return}if(aud){openAudience(aud.dataset.id,aud.dataset.publish==='true');return}if(manage){openMaintenance(manage.dataset.id);return}if(pub){if(!confirm('Unpublish this exam? Students will no longer be able to start it.'))return;pub.disabled=true;try{await call({action:'unpublish',examId:pub.dataset.id});await load()}catch(err){alert(err.message)}return}if(del){const x=exams.find(v=>v.id===del.dataset.id);if(!x)return;const code=examAccess(x)?.exam_code||'';const typed=prompt(`DELETE EXAM COMPLETELY\n\nThis removes questions, attempts, responses and results.\nType Exam Code ${code} to confirm:`);if(typed===null)return;try{await call({action:'delete',examId:x.id,confirmCode:typed});await load()}catch(err){alert(err.message)}}};
document.getElementById('logout').onclick=async()=>{await c.auth.signOut();location.replace('admin-login.html')};await load();
})();