-- Phase 3: exam syllabus range mapping and scope performance
-- Safe additive migration. Existing syllabus, exam attempts, responses and results are not rewritten.

create table if not exists neet_syllabus_subtopics (
  id bigint generated by default as identity primary key,
  chapter_id bigint not null references neet_syllabus_topics(id) on delete cascade,
  subtopic_title text not null check (length(btrim(subtopic_title)) > 0),
  sort_order integer not null default 0,
  status text not null default 'suggested' check (status in ('suggested','approved','disabled')),
  source text not null default 'auto' check (source in ('auto','admin')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index if not exists neet_syllabus_subtopics_active_title_uq
  on neet_syllabus_subtopics (chapter_id, lower(btrim(subtopic_title)))
  where status <> 'disabled';

create index if not exists neet_syllabus_subtopics_chapter_sort_idx
  on neet_syllabus_subtopics (chapter_id, sort_order, id);

create table if not exists exam_mapping_groups (
  id uuid primary key default gen_random_uuid(),
  exam_id uuid not null references exams(id) on delete cascade,
  subtopic_id bigint not null references neet_syllabus_subtopics(id),
  coverage text not null check (coverage in ('full','partial')),
  selector_text text not null check (length(btrim(selector_text)) > 0),
  sort_order integer not null default 0,
  created_by uuid references profiles(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists exam_mapping_groups_exam_sort_idx
  on exam_mapping_groups (exam_id, sort_order, id);
create index if not exists exam_mapping_groups_subtopic_idx
  on exam_mapping_groups (subtopic_id);

create table if not exists exam_question_syllabus_map (
  question_id uuid primary key references exam_questions(id) on delete cascade,
  exam_id uuid not null references exams(id) on delete cascade,
  mapping_group_id uuid not null references exam_mapping_groups(id) on delete cascade,
  subtopic_id bigint not null references neet_syllabus_subtopics(id),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists exam_question_syllabus_map_exam_idx
  on exam_question_syllabus_map (exam_id);
create index if not exists exam_question_syllabus_map_group_idx
  on exam_question_syllabus_map (mapping_group_id);
create index if not exists exam_question_syllabus_map_subtopic_idx
  on exam_question_syllabus_map (subtopic_id);

create table if not exists exam_scope_performance (
  id uuid primary key default gen_random_uuid(),
  attempt_id uuid not null references exam_attempts(id) on delete cascade,
  exam_id uuid not null references exams(id) on delete cascade,
  student_id uuid not null references profiles(id) on delete cascade,
  scope_level text not null check (scope_level in ('unit','chapter','topic')),
  unit_id bigint not null references neet_syllabus_units(id),
  chapter_id bigint references neet_syllabus_topics(id),
  subtopic_id bigint references neet_syllabus_subtopics(id),
  coverage text not null check (coverage in ('full','partial')),
  question_count integer not null default 0 check (question_count >= 0),
  max_marks numeric not null default 0,
  earned_marks numeric not null default 0,
  correct_count integer not null default 0 check (correct_count >= 0),
  wrong_count integer not null default 0 check (wrong_count >= 0),
  unattempted_count integer not null default 0 check (unattempted_count >= 0),
  percentage numeric not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint exam_scope_performance_scope_shape_ck check (
    (scope_level = 'unit' and chapter_id is null and subtopic_id is null)
    or (scope_level = 'chapter' and chapter_id is not null and subtopic_id is null)
    or (scope_level = 'topic' and chapter_id is not null and subtopic_id is not null)
  )
);

create unique index if not exists exam_scope_performance_unit_uq
  on exam_scope_performance (attempt_id, unit_id)
  where scope_level = 'unit';
create unique index if not exists exam_scope_performance_chapter_uq
  on exam_scope_performance (attempt_id, chapter_id)
  where scope_level = 'chapter';
create unique index if not exists exam_scope_performance_topic_uq
  on exam_scope_performance (attempt_id, subtopic_id)
  where scope_level = 'topic';
create index if not exists exam_scope_performance_student_idx
  on exam_scope_performance (student_id, scope_level, unit_id, chapter_id, subtopic_id);
create index if not exists exam_scope_performance_exam_idx
  on exam_scope_performance (exam_id);

create or replace view exam_scope_performance_sequenced as
select
  esp.*,
  a.submitted_at,
  a.attempt_no,
  row_number() over (
    partition by esp.student_id, esp.scope_level, esp.unit_id, esp.chapter_id, esp.subtopic_id
    order by a.submitted_at nulls last, a.attempt_no, esp.attempt_id
  )::integer as exam_sequence
from exam_scope_performance esp
join exam_attempts a on a.id = esp.attempt_id
where a.status in ('submitted','auto_submitted','graded');

alter table neet_syllabus_subtopics enable row level security;
alter table exam_mapping_groups enable row level security;
alter table exam_question_syllabus_map enable row level security;
alter table exam_scope_performance enable row level security;

-- New Phase-3 data is server-controlled. Admin and student access is through JWT-protected Edge Functions.
revoke select, insert, update, delete on neet_syllabus_subtopics from anon, authenticated;
revoke select, insert, update, delete on exam_mapping_groups from anon, authenticated;
revoke select, insert, update, delete on exam_question_syllabus_map from anon, authenticated;
revoke select, insert, update, delete on exam_scope_performance from anon, authenticated;
revoke select on exam_scope_performance_sequenced from anon, authenticated;

grant select, insert, update, delete on neet_syllabus_subtopics to service_role;
grant select, insert, update, delete on exam_mapping_groups to service_role;
grant select, insert, update, delete on exam_question_syllabus_map to service_role;
grant select, insert, update, delete on exam_scope_performance to service_role;
grant select on exam_scope_performance_sequenced to service_role;
grant usage, select on all sequences in schema public to service_role;
