import { SENDERS } from './policy.mjs'
const text=value=>String(value??'').trim()
const esc=value=>String(value??'').replace(/[&<>"']/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[ch]))
const months=['JAN','FEB','MAR','APR','MAY','JUN','JUL','AUG','SEP','OCT','NOV','DEC']
function dateLabel(value){const [y,m,d]=String(value||'').split('-').map(Number);return y&&m&&d?`${String(d).padStart(2,'0')} ${months[m-1]} ${y}`:String(value||'TODAY')}
function subjectData(tasks,subject){
  const rows=(Array.isArray(tasks)?tasks:[]).filter(x=>x.subject===subject)
  const study=rows.find(x=>x.task_type==='Study')||null
  const revision=rows.find(x=>x.task_type==='Revision')||null
  return {study,revision,hours:Math.max(1,Math.round((Number(study?.target_minutes)||240)/60))}
}
function card(subject,icon,tasks){
  const {study,revision,hours}=subjectData(tasks,subject)
  const chapter=study?.chapter||'No New Study'
  const day=study?.topic||'—'
  const revChapter=revision?.chapter||'No Revision'
  const revStage=revision?.topic||'—'
  return `<table role="presentation" width="100%" cellpadding="0" cellspacing="0" style="border-collapse:separate;border-spacing:0;margin:0 0 12px;background:#fff;border:1px solid #dbe6f1;border-radius:14px;overflow:hidden"><tr><td width="118" valign="middle" style="background:#0d3470;color:#fff;padding:18px 14px;text-align:center"><div style="font-size:22px;font-weight:800;color:#ff7a00">${esc(icon)}</div><div style="font-size:12px;font-weight:800;letter-spacing:.8px;margin-top:5px">${esc(subject.toUpperCase())}</div></td><td valign="top" style="padding:0"><table role="presentation" width="100%" cellpadding="0" cellspacing="0" style="border-collapse:collapse"><tr><td width="52%" style="padding:13px 16px;border-bottom:1px solid #e7edf4"><div style="font-size:9px;font-weight:800;color:#ff6b00;letter-spacing:.7px">STUDY</div><div style="font-size:14px;font-weight:800;color:#123b68;margin-top:4px;line-height:1.35">${esc(chapter)}</div></td><td width="24%" style="padding:13px 12px;border-bottom:1px solid #e7edf4;text-align:center"><div style="font-size:11px;font-weight:800;color:#123b68">${esc(day)}</div></td><td width="24%" rowspan="2" style="padding:14px 10px;text-align:center;border-left:1px solid #e7edf4;background:#f7faff"><div style="font-size:19px;font-weight:900;color:#123b68">${hours} HOURS</div></td></tr><tr><td style="padding:13px 16px"><div style="font-size:9px;font-weight:800;color:#ff6b00;letter-spacing:.7px">REVISION</div><div style="font-size:13px;font-weight:800;color:#123b68;margin-top:4px;line-height:1.35">${esc(revChapter)}</div></td><td style="padding:13px 12px;text-align:center"><div style="font-size:11px;font-weight:800;color:#123b68">${esc(revStage)}</div></td></tr></table></td></tr></table>`
}
export function buildMorningMessage({student={},date,tasks=[],siteUrl='https://sathyagrahiacademy.com'}={}){
  const name=text(student.full_name)||'Student',day=dateLabel(date),url=text(siteUrl)||'https://sathyagrahiacademy.com'
  const html=`<!doctype html><html><body style="margin:0;padding:0;background:#f3f7fc;font-family:Arial,Helvetica,sans-serif;color:#123b68"><table role="presentation" width="100%" cellpadding="0" cellspacing="0" style="background:#f3f7fc"><tr><td align="center" style="padding:20px 10px"><table role="presentation" width="680" cellpadding="0" cellspacing="0" style="width:100%;max-width:680px;background:#fff;border-radius:18px;overflow:hidden;border:1px solid #dce6f0"><tr><td style="background:#0b2f68;padding:16px 22px;color:#fff"><table role="presentation" width="100%"><tr><td><div style="font-size:16px;font-weight:900;letter-spacing:.5px">SATHYAGRAHI <span style="color:#ff7a00">ACADEMY</span></div><div style="font-size:9px;letter-spacing:1.2px;margin-top:3px;color:#dce9f8">NEET PREPARATION SYSTEM</div></td><td align="right" style="font-size:9px;font-weight:700;color:#dce9f8">DISCIPLINE TODAY<br><span style="color:#ff9a3d">A DOCTOR TOMORROW</span></td></tr></table></td></tr><tr><td style="padding:21px 22px 8px"><div style="font-size:13px;font-weight:800;color:#123b68">Good Morning, ${esc(name.toUpperCase())}! <span style="font-weight:500;color:#60748a">| Wishing you a focused study day.</span></div></td></tr><tr><td style="padding:8px 22px 18px;text-align:center"><div style="font-size:11px;color:#ff6b00;font-weight:900;letter-spacing:1.4px">MORNING STUDY PLAN</div><div style="font-size:28px;font-weight:900;color:#123b68;margin-top:5px">${esc(day)}</div><div style="font-size:11px;color:#6d7f92;margin-top:4px">Small Steps Big Results</div></td></tr><tr><td style="padding:0 22px 8px">${card('Biology','DNA',tasks)}${card('Chemistry','⚗',tasks)}${card('Physics','⚛',tasks)}</td></tr><tr><td style="padding:18px 22px;background:#f8fbff;border-top:1px solid #e3ebf3"><div style="font-size:9px;font-weight:900;color:#ff6b00;letter-spacing:1px">TODAY’S FOCUS</div><div style="font-size:12px;color:#123b68;font-weight:700;margin-top:5px">Complete today’s study as per plan and maintain your notes.</div><div style="font-size:10px;color:#75879a;margin-top:13px">Sathyagrahi Academy · NEET Preparation System</div><div style="font-size:9px;color:#123b68;font-weight:800;letter-spacing:.8px;margin-top:4px">CONSISTENT EFFORTS <span style="color:#ff7a00">|</span> BRIGHTER FUTURES</div></td></tr></table></td></tr></table></body></html>`
  const lines=['Biology','Chemistry','Physics'].map(subject=>{const d=subjectData(tasks,subject);return `${subject}: ${d.study?.chapter||'No New Study'} (${d.study?.topic||'—'}); ${d.revision?`${d.revision.chapter} ${d.revision.topic}`:'No Revision'}; ${d.hours} HOURS`})
  return {from:SENDERS.morning_plan,senderName:'Sathyagrahi Academy',subject:`Morning Study Plan — ${day}`,html,text:`Good Morning, ${name}!\n${lines.join('\n')}\n${url}`}
}
